[package]
name = "binary_package"
version = "0.1.0"
authors = ["Saad Shakoor <saadshakoorofficial@gmail.com>"]
edition = "2018"

# See more keys and theircargo run definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_package = { path = "../lib_package" }